[package]
authors = ["Nicolas Di Prima <nicolas@primetype.co.uk>", "Vincent Hanquez <vincent@typed.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "wallet-core"
version = "0.5.0-pre3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
bip39 = {path = "../../bip39"}
chain-addr = {path = "../../chain-deps/chain-addr"}
chain-core = {path = "../../chain-deps/chain-core"}
chain-crypto = {path = "../../chain-deps/chain-crypto"}
chain-impl-mockchain = {path = "../../chain-deps/chain-impl-mockchain"}
chain-path-derivation = {path = "../../chain-path-derivation"}
chain-ser = {path = "../../chain-deps/chain-ser"}
hdkeygen = {path = "../../hdkeygen"}
symmetric-cipher = {path = "../../symmetric-cipher"}
thiserror = {version = "1.0.13", default-features = false}
wallet = {path = "../../wallet"}
cryptoxide = "0.1"
