[package]
name = "wallet"
version = "0.6.0-pre.1"
authors = ["Nicolas Di Prima <nicolas@primetype.co.uk>", "Vincent Hanquez <vincent@typed.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cryptoxide = "0.4.2"
ed25519-bip32 = "0.4.0"
cbor_event = "^2.1.3"
thiserror = { version = "1.0.13", default-features = false }
bip39 = { path = "../bip39" }
chain-path-derivation = { path = "../chain-path-derivation" }
hdkeygen = { path = "../hdkeygen" }
hex = "0.4.2"
itertools = "0.9"
hashlink = "0.7.0"
zeroize = "1.5.3"

chain-time = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-crypto = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-addr = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
cardano-legacy-address = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
imhamt = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
chain-ser = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
