package com.iohk.jormungandrwallet;

public enum ErrorCode {
    INVALID_INPUT,
    WALLET_RECOVERING,
    WALLET_CONVERSION,
    WALLET_VOTE_OUT_OF_RANGE,
    WALLET_TRANSACTION_BUILDING,
    SYMMETRIC_CIPHER_ERROR,
    SYMMETRIC_CIPHER_INVALID_PASSWORD,
    INVALID_VOTE_ENCRYPTION_KEY
}