[package]
name = "hdkeygen"
version = "0.2.0"
authors = ["Nicolas Di Prima <nicolas@primetype.co.uk>", "Vincent Hanquez <vincent@typed.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cryptoxide = "0.3.1"
ed25519-bip32 = "0.4.0"
bip39 = { path = "../bip39" }
cbor_event = "^2.1.3"
thiserror = { version = "1.0.13", default-features = false }
chain-path-derivation = { path = "../chain-path-derivation" }
hex = "0.4.2"

chain-crypto = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "remove-deprecated-definition" }
chain-addr = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "remove-deprecated-definition" }
cardano-legacy-address = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "remove-deprecated-definition" }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
